"use client";

import { useState } from "react";

const content = {
  en: {
    date: "February 16, 2026",
    label: "Policy & Security",
    title:
      "China 2025 — Comprehensive AI Measures and What They Mean for Security",
    lead:
      "A review of China's 2025 regulatory changes, how new labeling and disclosure obligations reshape AI services, and what recent deepfake video‑conference attacks signal for security.",
    sections: [
      {
        title: "Summary",
        paragraphs: [
          "In recent years, China has developed a set of measures focused on generative AI and “deep synthesis” content. In 2025, additional obligations came into force targeting transparency, labeling of AI‑generated content, and registration of services that can influence public opinion. These reforms arrive amid growing abuse — especially incidents where attackers used deepfake video and audio to deceive employees during video conferences."
        ]
      },
      {
        title: "Regulatory baseline — what already existed",
        paragraphs: [
          "China's generative‑AI framework took a significant step in July 2023 with the release of the “Interim Measures for the Management of Generative AI Services,” effective August 2023. These measures introduced administrative obligations for providers — registration, content controls, and disclosure of model identity and safety procedures. Through 2024–2025, this baseline was expanded with new rules and standards."
        ]
      },
      {
        title:
          "2025: comprehensive measures focused on transparency and labeling",
        paragraphs: [
          "In 2025, Chinese agencies (led by the Cyberspace Administration of China — CAC) finalized and released concrete requirements for labeling AI‑generated content and national technical standards. Examples include:",
          "• mandatory labeling of any content fully or partially generated by AI (text, images, audio, video), under detailed methods and standards (national standard GB 45438-2025);",
          "• registration and submission requirements for generative‑AI services that affect public opinion;",
          "• stricter rules for storage and protection of training data, plus tighter controls on personal data and cross‑border transfers;",
          "• obligations to implement complaint mechanisms and oversight of harmful content, with inspection and sanctions by regulators.",
          "These measures are part of a broader strategy: manage risks from large‑scale use of generative AI while encouraging domestic development under state oversight and legal frameworks."
        ]
      },
      {
        title: "Technical and operational requirements for providers",
        paragraphs: [
          "The new standards impose not only legal obligations but practical engineering requirements:",
          "• viewability: tools must clearly and persistently declare when content is AI‑generated or modified;",
          "• traceability: systems must retain logs, versions, and metadata about sources and model parameters used to generate content;",
          "• pre‑deployment testing: public models must pass safety checks, including scenarios of misuse;",
          "• incident reporting: mandatory reporting of significant incidents and procedures to remove harmful content."
        ]
      },
      {
        title:
          "Deepfake video‑conference attacks — why they matter",
        paragraphs: [
          "In the business world, major attacks have already used deepfake technologies (voice clones and synthetic video) to impersonate executives and persuade employees on video calls to make transfers or disclose sensitive information. These cases show how quickly generative techniques move from “synthesis” to real security threats. Earlier incidents include high‑profile frauds in Europe and the UK where fake audio/video resulted in million‑dollar losses.",
          "In the China context, the potential for mass dissemination of fabricated content in business or public channels makes labeling and traceability critical tools to identify and reconstruct attack sources."
        ]
      },
      {
        title:
          "What it means for AI providers and for HRI/robotics",
        paragraphs: [
          "For companies developing AI solutions (including robotics), the message is straightforward: regulatory obligations are now part of technical and business risk. Providers and integrators must:",
          "• implement mandatory labeling and user disclosures;",
          "• keep detailed records of training data and model parameters;",
          "• build mechanisms for rapid response and removal of harmful content;",
          "• develop security protocols that prevent generative agents from autonomously initiating external communications without supervision.",
          "Especially in HRI and robotic systems — where synthetic voice/visual outputs can be used in interactions with users or operators — labeling and control become an added safety layer."
        ]
      },
      {
        title: "How to prepare — practical steps",
        paragraphs: [
          "Recommended operational steps that FUA Robotics (and others) can implement:",
          "• add automatic labeling of generated content in UI/UX (text banners, audio tags, metadata);",
          "• run internal red‑team exercises for deepfake and social‑engineering scenarios;",
          "• ensure audit logs for models and data lineage (who, when, with which prompt/parameters);",
          "• include incident response plans and regulator notification mechanisms for serious events."
        ]
      },
      {
        title: "Conclusion",
        paragraphs: [
          "China's 2025 measures establish a clear governance matrix: greater transparency, labeling obligations, and stricter operational requirements. They are a response to real threats — from disinformation to sophisticated video‑conference fraud. For development teams and engineers, this means security, reproducibility, and auditability are no longer “nice‑to‑have” — they are regulated responsibilities."
        ]
      }
    ]
  },
  hr: {
    date: "16. veljače 2026.",
    label: "Policy & Security",
    title:
      "Kina 2025 — Sveobuhvatne mjere za umjetnu inteligenciju i rizik deepfake napada",
    lead:
      "Pregled ključnih regulatornih promjena u Kini 2025., kako nove obveze označavanja i izdavanja podataka mijenjaju pejzaž za pružatelje AI usluga te što nam govore nedavni slučajevi deepfake napada kroz video‑konferencije.",
    sections: [
      {
        title: "Sažetak",
        paragraphs: [
          "Kina je u posljednim godinama razvila niz mjera usmjerenih na generativnu umjetnu inteligenciju i “deep synthesis” sadržaj. U 2025. su stupile na snagu dodatne obveze koje ciljaju transparentnost, označavanje AI‑generiranog sadržaja i jasnu registraciju usluga koje mogu utjecati na javno mnijenje. Ove reforme dolaze u kontekstu sve učestalijih zloupotreba — posebno slučajeva u kojima su napadači koristili deepfake video i audio tehnologije kako bi prevarili zaposlenike tijekom video‑konferencija."
        ]
      },
      {
        title: "Regulatorni okvir — što je već postojalo",
        paragraphs: [
          "Kineski okvir za generativnu AI započeo je značajnim korakom u srpnju 2023. kada su objavljene “Interim Measures for the Management of Generative AI Services” koje su stupile na snagu u kolovozu 2023. Te mjere su prve administrativne obveze posebno usmjerene prema pružateljima generativnih AI usluga — zahtijevale su registraciju, određene kontrole sadržaja i obvezu objave identiteta modela i sigurnosnih postupaka. Ove osnove su tijekom 2024.–2025. proširene i dopunjene kroz nova pravila i standarde."
        ]
      },
      {
        title:
          "2025: nove, sveobuhvatne mjere fokusirane na transparentnost i označavanje",
        paragraphs: [
          "U 2025. kineske su agencije (predvođene Cyberspace Administration of China — CAC) finalizirale i objavile konkretne zahtjeve za označavanje AI‑generiranog sadržaja i nacionalne tehničke standarde. Primjeri obveza uključuju:",
          "• obvezu označavanja svakog sadržaja koji je u potpunosti ili djelomično generirao AI (tekst, slike, audio, video), prema novim mjerama koje postavljaju detaljne metode označavanja i standarde (nacionalni standard GB 45438-2025);",
          "• obvezu registracije i podnošenja informacija za pružatelje usluga generativne AI koji utječu na javno mnijenje;",
          "• zahtjeve za pohranu i zaštitu podataka korištenih za treniranje modela, te strože kontrole osobnih podataka i prijenosa podataka;",
          "• obveze za implementaciju mehanizama za pritužbe i nadzor nad štetnim sadržajem, uz mogućnost inspekcije i sankcija od strane regulatora.",
          "Takve su mjere zamišljene kao dio šire strategije: kontrolirati rizike koji proizlaze iz masovne upotrebe generativnih AI alata dok se istovremeno potiče domaći razvoj tehnologije pod državnim nadzorom i pravnim okvirom."
        ]
      },
      {
        title: "Tehnički i operativni zahtjevi za pružatelje usluga",
        paragraphs: [
          "Novi standardi ne ostavljaju samo pravne obveze — oni nameću i praktične, inženjerske zahtjeve:",
          "• viewability: alati moraju jasno i trajno deklarirati kada je sadržaj generiran ili modificiran AI‑jem;",
          "• traceability: sustavi moraju zadržavati zapisnike, verzije i metapodatke o izvorima i parametrima modela koji su generirali sadržaj;",
          "• pre‑deployment testing: modeli koji će biti javno dostupni prolaze kroz sigurnosne provjere, uključujući provjeru za rizične scenarije zlouporabe;",
          "• incident reporting: obavezno prijavljivanje većih incidenata, te operativne procedure za uklanjanje štetnog sadržaja."
        ]
      },
      {
        title: "Video‑konferencijski deepfake napadi — zašto su relevantni",
        paragraphs: [
          "U poslovnom svijetu već su zabilježeni veliki napadi u kojima su napadači koristili deepfake tehnologije (glasovne klonove i sintetički video) kako bi imitirali izvršne ljude i preko video‑poziva uvjerili zaposlenike da izvedu novčane transfere ili otkriju povjerljive informacije. Ti incidenti pokazuju koliko brzo generativne tehnike mogu prijeći iz “sinteze” u stvarnu sigurnosnu prijetnju. Primjeri ranijih napada uključuju poznate velike prevare u Europi i Velikoj Britaniji gdje su lažni audio‑/video prikazi doveli do milijunskih financijskih gubitaka.",
          "U kontekstu Kine, upravo zbog potencijala masovne diseminacije i širenja lažnog sadržaja unutar poslovnih ili javnih komunikacijskih kanala, obveze označavanja i traceability postaju ključni instrumenti za pronalaženje i rekonstrukciju izvora napada."
        ]
      },
      {
        title: "Što to znači za pružatelje AI rješenja i za HRI/robotiku?",
        paragraphs: [
          "Za tvrtke koje razvijaju AI rješenja (uključujući one u robotici) poruka je jednostavna: regulatorne su obveze postale dio tehničkog i poslovnog rizika. Pružatelji modela i integratori moraju:",
          "• implementirati obavezno označavanje i korisničke informacije;",
          "• voditi detaljne zapise o podacima za treniranje i parametrima modela;",
          "• izgraditi mehanizme za brzu reakciju i uklanjanje štetnog sadržaja;",
          "• razvijati sigurnosne protokole koji sprječavaju da generativni agenti autonomno pokreću vanjske komunikacijske kanale bez nadzora.",
          "Posebno u HRI i robotskim sustavima, gdje se digitalni sadržaj i glasovne/vidne sintetske izlaze mogu koristiti u interakciji s korisnicima ili operaterima, zahtjev za označavanjem i kontrolom postaje dodatni sloj sigurnosnog dizajna."
        ]
      },
      {
        title: "Kako se pripremiti — praktični koraci",
        paragraphs: [
          "Preporučeni operativni koraci koje FUA Robotics (i druge tvrtke) mogu provesti:",
          "• uvesti automatsko označavanje generiranog sadržaja u UI/UX (tekstualni banneri, audio oznake, metapodaci);",
          "• implementirati internu “red team” provjeru za scenarije deepfake napada i socijalnog inženjeringa;",
          "• osigurati audit‑logove modela i podatkovne linije (tko, kada, s kojim promptom/parametrima);",
          "• obavezno uključiti plan odgovora na incidente i mehanizme obavještavanja regulatora u slučaju ozbiljnih incidenata."
        ]
      },
      {
        title: "Zaključak",
        paragraphs: [
          "Kineske mjere 2025. stvaraju jasnu upravljačku matricu: povećana transparentnost, obveze označavanja i stroži operativni zahtjevi. One su odgovor na stvarne prijetnje — od dezinformacija do sofisticiranih video‑konferencijskih prijevara. Za razvojne timove i inženjere to znači da sigurnost, reproducibilnost i auditabilnost više nisu samo “lijepi dodatci” — već regulirana odgovornost."
        ]
      }
    ]
  }
};

function Paragraph({ text }: { text: string }) {
  if (text.startsWith("• ")) {
    return <li>{text.slice(2)}</li>;
  }
  if (/^\d+\.\s/.test(text)) {
    return <li>{text.replace(/^\d+\.\s/, "")}</li>;
  }
  return <p>{text}</p>;
}

export default function Post() {
  const [lang, setLang] = useState<"en" | "hr">("en");
  const t = content[lang];

  return (
    <main className="bg-white text-neutral-900 min-h-screen">
      <header className="flex flex-wrap items-center justify-between gap-4 px-8 py-8">
        <div className="flex items-center gap-6">
          <a
            href="/"
            className="text-sm font-medium text-neutral-800 hover:text-neutral-600"
          >
            FUA Robotics
          </a>
          <a
            href="/blog"
            className="text-sm font-medium text-neutral-700 hover:text-neutral-500"
          >
            Blog
          </a>
        </div>
        <div className="flex gap-4">
          <button
            onClick={() => setLang("hr")}
            className={`px-4 py-2 rounded-full text-sm border transition ${
              lang === "hr" ? "bg-black text-white" : "hover:bg-gray-100"
            }`}
          >
            🇭🇷 Hrvatski
          </button>
          <button
            onClick={() => setLang("en")}
            className={`px-4 py-2 rounded-full text-sm border transition ${
              lang === "en" ? "bg-black text-white" : "hover:bg-gray-100"
            }`}
          >
            🇬🇧 English
          </button>
        </div>
      </header>

      {/* HERO */}
      <section className="border-b border-neutral-200">
        <div className="max-w-5xl mx-auto px-6 py-20">
          <p className="text-sm uppercase tracking-wide text-neutral-500 mb-2">
            {t.label}
          </p>
          <p className="text-xs uppercase tracking-[0.2em] text-neutral-400 mb-4">
            {t.date}
          </p>
          <h1 className="text-3xl md:text-4xl font-semibold mb-4">
            {t.title}
          </h1>
          <p className="text-lg text-neutral-600 max-w-3xl">
            {t.lead}
          </p>
        </div>
      </section>

      {/* ARTICLE */}
      <article className="max-w-3xl mx-auto px-6 py-12 space-y-8 leading-relaxed text-[17px]">
        {t.sections.map((section) => {
          const bullets = section.paragraphs.filter((p) => p.startsWith("• "));
          const ordered = section.paragraphs.filter((p) => /^\d+\.\s/.test(p));
          const normal = section.paragraphs.filter(
            (p) => !p.startsWith("• ") && !/^\d+\.\s/.test(p)
          );

          return (
            <section key={`${section.title}-${section.paragraphs[0]}`} className="space-y-4">
              <h2 className="text-2xl font-semibold">{section.title}</h2>

              {normal.map((text) => (
                <Paragraph key={text} text={text} />
              ))}

              {bullets.length ? (
                <ul className="list-disc pl-6 space-y-2">
                  {bullets.map((text) => (
                    <Paragraph key={text} text={text} />
                  ))}
                </ul>
              ) : null}

              {ordered.length ? (
                <ol className="list-decimal pl-6 space-y-2">
                  {ordered.map((text) => (
                    <Paragraph key={text} text={text} />
                  ))}
                </ol>
              ) : null}
            </section>
          );
        })}
      </article>


    </main>
  );
}
